image: go1.4
notify:
  email:
    recipients:
    - drone@clever.com
  slack:
    on_failure: true
    on_started: false
    on_success: false
    webhook_url: $$slack_webhook
publish:
  docker:
    docker_host: $$docker_server
    email: $$docker_email
    image_name: clever/district-authorizations
    password: $$docker_password
    registry_login: true
    tags:
    - $(git rev-parse --short HEAD)
    username: $$docker_username
    when:
      branch: master
script:
- env
- sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10
- sudo echo 'deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen'
  | sudo tee /etc/apt/sources.list.d/mongodb.list
- sudo apt-get update
- sudo apt-get install mongodb-org
- mongo --eval 'rs.initiate()'
- make test
services:
- clever/mongo:2.4
